### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-1#33]
*Congratulations on finishing milestone 2! We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### Code is abstracted to functions with good function design

- [ ] There are cases of functions that are too big and could be improved by defining utility functions. **-1**

`plot_square_data`

- [ ] There are cases of functions that have very obscure names. **- 1**

`list_abs`

- [ ] Functions do not follow a consistent style. **-1**

`splitxy` does not use snake case like the other two functions

- [ ] There are cases of functions with questionable internal design. **- 1**

`plot_square_data` has 4 nested if statements.

### Functions are well documented

- [ ]  One or more functions are only partially understood from reading their documentation. **- 0.5**

`list_abs`

- [ ] One or more documentations could be improved through additional proofreading (i.e., spelling and grammatical errors are present). **- 1**

`list_abs`, `splitxy`

### Tests suite is of high quality

- [ ] There are cases of functions that do not test at least 1 edge-case input. **- 3**

`Test_listfun`, `Test_Square_Plot`, `Test_splitxy`. You could test empty data frames for instance.

###  Analysis can be run reproducibly using documentation provided in the README

- [ ] I could not reproduce the analysis because I ran `docker run -it danielhou13/dsci-310-project` and none of the avaiable links worked. The docker command is probably missing a port argument. **- 3**

- [ ] I could not reproduce the analysis because there is no repository available inside the container. The docker command is probably missing a volume argument. **- 3**

- [ ] Clearly specify usage instructions to the point a user could copy and paste them and they would work. **- 2**

There are no instructions on how to run the jupyter notebook, which I tried to and got an error as explained in the "The functions work as expected (tests and analysis will tell us this)" section.

**Comment by danielhou13** [comment]
"Analysis can be run reproducibly using documentation provided in the README"

https://github.com/DSCI-310/DSCI-310-Group-1

The instruction steps should include how to open the Jupyter Lab and run the analysis successfully now.

**Comment by danielhou13** [comment]
Test_splitxy now has an edge case test (last test)

https://github.com/DSCI-310/DSCI_310_group_1_package/blob/main/tests/test_splitxy.py
