### ISSUE TITLE
Milestone 3 feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-1#43]
## Rubric
- 23 / 25: Analysis code is abstracted to four (or more) scripts which take command line arugments and save analysis artifacts (e.g., figures and data for tables).
- 23 / 25: Report is written in a literate code document, and the code in the literate code document primarily functions to source analysis artifacts and format the document.
- 23 / 25: A data analysis pipeline written in GNU Make exists, and works to run the analysis from beginning to end, as well as to clean up the analysis
- 2 / 2: Dependencies have been updated (so it include the test libraries)
- 2 / 2: Project file and directory structure organization
- 2 / 2: GitHub Project board
- 2 / 2: GitHub Issue Milestones
- 2 / 2: Follows GitHub flow version control workflow
- 2 / 2: GitHub release
- 13 / 13: Analysis can be run reproducibly using documentation provided in the README.

## Commonly provided feedback

Recommended to open an issue in the project's repository to provide this feedback so students can act on it.
In milestone 4, these things will be regraded as part of the final grade for the project.
Bolded points indicate how many points should be taken off the rubric for each of these.
These numbers do not need to be included in the GitHub issue.

Text to copy and paste into GitHub issue before providing specific comments:

*Congratulations on finishing milestone 2! We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### Analysis code is abstracted to four (or more) scripts which take command line arguments and save analysis artifacts (e.g., figures and data for tables).

- [ ] One or more scripts are not well organized **- 2**

`src/generate_exploratory.py` could abstract `generate_figure` and maybe `generator` functions to another file.

`src/regression.py` could also abstract some functions

### Report is written in a literate code document, and the code in the literate code document primarily functions to source analysis artifacts and format the document.

- [ ] The literate code document (R Markdown or Jupyter notebook) does not use code to automatically update inline values generated from the analysis that are presented in the narrated text of the document but it does not work correctly or a few missing cases. **- 2**

There a few hard coded values like "train test split of 80% training and 20% testing" and " where moderately low (396)".

- [ ] **(I did not take off points for that)** Consider rounding printed values. For instance, "studytime = 316.000000" could be "studytime = 316". Another example, "coefficient = 0.910598" could be "coefficient = 0.9"

### A data analysis pipeline written in GNU Make exists, and works to run the analysis from beginning to end, as well as to clean up the analysis

- [ ] Target `all` could be simplified by writing something like `all: <report_target>`. **- 2**

###  Analysis can be run reproducibly using documentation provided in the README

- [ ] **(I did not take off points for that)** In README, `How to run?` section, consider using `#` for code comments instead of `<!-- -->`. `#` is the correct symbol for comments in both git bash and powershell
