### ISSUE TITLE
Milestone 4 feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-1#44]
*Congratulations on finishing your final project!!! This is a great accomplishment and you should be proud!
Below we list some specific feedback you can use to improve your project if you so desire,
but most importantly to learn.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### Addressed feedback given by the teaching team from milestone 1

- [ ] 20% or less of the feedback given by the teaching team from milestone 1 was not addressed **-5**

Do note that the Dockerfile feedback was incorrectly addressed.

### Addressed feedback given by the teaching team from milestone 2

- [ ] 20% or less of the feedback given by the teaching team from milestone 2 was not addressed **-5**

###  Analysis can be run reproducibly using documentation provided in the README

- [ ] Usage documentation could be improved for clarity (i.e., it is not explicitly clear to the user how to use the project, or some of the wording is confusing). **-1**

`makefile all` in "Reproduce the report" should be `make all`
